[project]
name = "app"
version = "0.1.0"
description = "Caso de Estudio: Optimización de la Atención al Cliente en una Empresa de E-commerce"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-ai-inference>=1.0.0b9",
    "python-dotenv>=1.0.0",
]
